# Generated by Django 6.0.8 on 2026-10-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('friend_request', 'Solicitud de amistad'), ('friend_accepted', 'Solicitud aceptada'), ('group_added', 'Te agregaron a un grupo'), ('group_event', 'Junta nueva en un grupo'), ('event_changed', 'Cambió una junta'), ('event_reminder', 'Recordatorio de junta'), ('event_cancelled', 'Se canceló una junta'), ('event_reactivated', 'Se reactivó una junta')], max_length=20),
        ),
    ]
