# Generated by Django 6.0.8 on 2026-10-04 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(default='#b9a6f2', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Usa un color hexadecimal, p. ej. #b9a6f2.')]),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Día'), ('dark', 'Noche'), ('system', 'Automático')], default='system', max_length=10),
        ),
    ]
