# Generated by Django 6.0.8 on 2026-10-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_decor',
            field=models.BooleanField(default=True, verbose_name='Figuras de fondo'),
        ),
    ]
