# Generated by Django 6.0.8 on 2026-10-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='money_mode',
            field=models.CharField(choices=[('none', 'Sin dinero'), ('fixed', 'Cuota fija'), ('shared', 'Gastos compartidos')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='arrival',
            field=models.CharField(blank=True, choices=[('on_time', 'Llegó a tiempo'), ('late', 'Llegó tarde'), ('absent', 'No llegó')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='has_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
