# Generated by Django 6.0.8 on 2026-10-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bring_list_enabled',
            field=models.BooleanField(default=True, verbose_name='Qué llevar'),
        ),
        migrations.AddField(
            model_name='event',
            name='comments_enabled',
            field=models.BooleanField(default=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='event',
            name='polls_enabled',
            field=models.BooleanField(default=True, verbose_name='Votaciones'),
        ),
    ]
