# Generated by Django 6.0.8 on 2026-10-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo de la cancelación'),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
