# Generated by Django 6.0.8 on 2026-10-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='gif_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='gif_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='gif_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='chat/%Y/%m/', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
