# Generated by Django 6.0.8 on 2026-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, upload_to='groups/'),
        ),
    ]
